const FORBIDDEN_PREFIXES = [
  'image of',
  'picture of',
  'photo of',
  'photograph of',
  'a image',
  'an image',
  'a photo',
  'an photo',
  'a picture',
  'an picture',
]

export function validateAltText(text, maxLength = 125) {
  const issues = []

  if (text === undefined) {
    return { valid: false, issues: ['Missing alt text'], text: '' }
  }

  if (typeof text !== 'string') {
    return { valid: false, issues: ['Alt text must be a string'], text: '' }
  }

  const trimmed = text.trim()

  if (trimmed.length > maxLength) {
    issues.push(`Exceeds ${maxLength} characters (${trimmed.length})`)
  }

  const lower = trimmed.toLowerCase()
  for (const prefix of FORBIDDEN_PREFIXES) {
    if (lower.startsWith(prefix)) {
      issues.push(`Starts with forbidden prefix: "${prefix}"`)
      break
    }
  }

  if (/\.(jpg|jpeg|png|gif|webp|svg|bmp|tiff?)/i.test(trimmed)) {
    issues.push('Contains file extension')
  }

  if (/generated by ai|ai-generated|chatgpt|copilot|gpt-4|claude/i.test(trimmed)) {
    issues.push('Contains AI mention')
  }

  if (/^\w+[-_]\d+$/i.test(trimmed)) {
    issues.push('Appears to be a filename')
  }

  const words = trimmed.toLowerCase().split(/\s+/)
  const wordCount = {}
  for (const word of words) {
    if (word.length > 3) {
      wordCount[word] = (wordCount[word] || 0) + 1
    }
  }
  const repeatedWords = Object.entries(wordCount).filter(([, count]) => count > 2)
  if (repeatedWords.length > 0) {
    issues.push('Possible keyword stuffing detected')
  }

  return {
    valid: issues.length === 0,
    issues,
    text: trimmed,
  }
}

export function sanitizeAltText(text, maxLength = 125) {
  if (!text || typeof text !== 'string') {
    return ''
  }

  let sanitized = text.trim()

  const lower = sanitized.toLowerCase()
  for (const prefix of FORBIDDEN_PREFIXES) {
    if (lower.startsWith(prefix)) {
      sanitized = sanitized.slice(prefix.length).trim()
      if (sanitized.startsWith(',') || sanitized.startsWith(':')) {
        sanitized = sanitized.slice(1).trim()
      }
      break
    }
  }

  sanitized = sanitized.charAt(0).toUpperCase() + sanitized.slice(1)

  if (sanitized.length > maxLength) {
    sanitized = sanitized.slice(0, maxLength - 1).trim() + '…'
  }

  return sanitized
}
