import { describe, it, expect } from 'vitest'
import { validateAltText, sanitizeAltText } from '../../src/main/utils/validation.js'

describe('validateAltText', () => {
  it('accepts valid alt text', () => {
    const result = validateAltText('A golden retriever playing in the park')
    expect(result.valid).toBe(true)
    expect(result.issues).toHaveLength(0)
  })

  it('accepts empty alt text for decorative images', () => {
    const result = validateAltText('')
    expect(result.valid).toBe(true)
  })

  it('rejects alt text exceeding max length', () => {
    const longText = 'A'.repeat(150)
    const result = validateAltText(longText, 125)
    expect(result.valid).toBe(false)
    expect(result.issues).toContain('Exceeds 125 characters (150)')
  })

  it('rejects alt text starting with "Image of"', () => {
    const result = validateAltText('Image of a sunset over the ocean')
    expect(result.valid).toBe(false)
    expect(result.issues[0]).toMatch(/forbidden prefix/)
  })

  it('rejects alt text starting with "Picture of"', () => {
    const result = validateAltText('Picture of mountains')
    expect(result.valid).toBe(false)
    expect(result.issues[0]).toMatch(/forbidden prefix/)
  })

  it('rejects alt text starting with "Photo of"', () => {
    const result = validateAltText('Photo of a family gathering')
    expect(result.valid).toBe(false)
    expect(result.issues[0]).toMatch(/forbidden prefix/)
  })

  it('rejects alt text containing file extensions', () => {
    const result = validateAltText('Beautiful sunset IMG_1234.jpg')
    expect(result.valid).toBe(false)
    expect(result.issues).toContain('Contains file extension')
  })

  it('rejects alt text mentioning AI', () => {
    const cases = [
      'AI-generated sunset',
      'Generated by AI assistant',
      'ChatGPT describes this as a dog',
      'Copilot created this description',
    ]

    for (const text of cases) {
      const result = validateAltText(text)
      expect(result.valid).toBe(false)
      expect(result.issues).toContain('Contains AI mention')
    }
  })

  it('detects keyword stuffing', () => {
    const result = validateAltText('shoes shoes shoes running shoes athletic shoes')
    expect(result.valid).toBe(false)
    expect(result.issues).toContain('Possible keyword stuffing detected')
  })

  it('detects filename-like patterns', () => {
    const result = validateAltText('IMG_1234')
    expect(result.valid).toBe(false)
    expect(result.issues).toContain('Appears to be a filename')
  })

  it('handles undefined input', () => {
    const result = validateAltText(undefined)
    expect(result.valid).toBe(false)
    expect(result.issues).toContain('Missing alt text')
  })

  it('handles non-string input', () => {
    const result = validateAltText(123)
    expect(result.valid).toBe(false)
    expect(result.issues).toContain('Alt text must be a string')
  })

  it('trims whitespace', () => {
    const result = validateAltText('  A sunset over the ocean  ')
    expect(result.valid).toBe(true)
    expect(result.text).toBe('A sunset over the ocean')
  })
})

describe('sanitizeAltText', () => {
  it('removes forbidden prefixes', () => {
    expect(sanitizeAltText('Image of a dog')).toBe('A dog')
    expect(sanitizeAltText('Picture of sunset')).toBe('Sunset')
    expect(sanitizeAltText('Photo of: mountains')).toBe('Mountains')
  })

  it('capitalizes first letter', () => {
    expect(sanitizeAltText('sunset over ocean')).toBe('Sunset over ocean')
  })

  it('truncates to max length with ellipsis', () => {
    const longText = 'A'.repeat(150)
    const result = sanitizeAltText(longText, 125)
    expect(result.length).toBe(125)
    expect(result.endsWith('…')).toBe(true)
  })

  it('handles empty input', () => {
    expect(sanitizeAltText('')).toBe('')
    expect(sanitizeAltText(undefined)).toBe('')
  })
})
